update main and app
Beam-Data-Company/beam-early-access pull request #1
Opened 2021-06-23 05:18 UTC by mingsorawit

- change js file to tsx file
- change css
- create page structure

2021-06-24 12:12 UTC, mingsorawit commented
install npm i react-mailchimp-subscribe
create basic form that connects with beamdata mailchimp

2021-06-24 15:43 UTC, oukunanan requested changes

2021-06-24 15:43 UTC, oukunanan commented on styles/Home.module.css
> +  /*width: 631px;*/
Remove

2021-06-24 15:43 UTC, oukunanan commented on styles/Home.module.css
> +  font-style: normal;*/
Remove

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +  console.log(message);
Remove consoe.log

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +    if(event.target){
Why we need this `if` here?

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +    email.indexOf("@") > -1 &&
Why we need this?

2021-06-24 15:43 UTC, oukunanan commented on pages/index.tsx
> +      <div className={styles.header}>Beam</div>
I thougt P'Sandee already import the logo

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +const CustomForm = ({ status, message, onValidated }: Props) => {
And prefer normal function than arrow function
https://kentcdodds.com/blog/function-forms

2021-06-24 15:43 UTC, oukunanan commented on package.json
> +    "dotenv": "^10.0.0",
I think we can config `next.config.js` instead of install this package.

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +import React, { useState }from "react";
So we gonna have url `/form` ? according to your file name

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +    alert('An email was submitted')
Remove

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +const MailchimpFormContainer = () => {
Convert to normal function

2021-06-24 15:43 UTC, oukunanan commented on pages/index.tsx
> +        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
Save font to `public` folder and use font-face to import the font in global.css

2021-06-24 15:43 UTC, oukunanan commented on pages/index.tsx
> +        {/* <div className={styles.grid}>
Please remove unused code entire project.

2021-06-24 15:43 UTC, oukunanan commented on styles/Home.module.css
> +  letter-spacing: normal;
Why?

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +    <form className="mc__form" onSubmit={(event) => handleSubmit(event)}>
```suggestion
    <form className="mc__form" onSubmit={handleSubmit}>
```

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +        <input type="email" value={email} placeholder="your@email.com" onChange={(event) => handleChange(event)} required/>
```suggestion
        <input type="email" value={email} placeholder="your@email.com" onChange={handleChange} required/>
```

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +    <div className="mc__form-container">
Where these className come from?

2021-06-24 15:43 UTC, oukunanan commented on pages/form.tsx
> +            onValidated={formData => subscribe(formData)}
Can we do this?
```suggestion
            onValidated={subscribe}
```

2021-06-24 15:44 UTC, oukunanan commented
Please also put design url within PR description.

2021-06-25 08:20 UTC, mingsorawit commented
update code as suggested
display message when submit form depends on status
status could be success/error/sending
![Screenshot (1116)](https://user-images.githubusercontent.com/70103668/123394010-df368600-d5c8-11eb-889f-475d682702de.png)
![Screenshot (1117)](https://user-images.githubusercontent.com/70103668/123394016-e067b300-d5c8-11eb-946f-2cc7d3991426.png)

2021-06-28 09:00 UTC, oukunanan approved these changes
Approved but will do refactor in the future PR.

2021-06-28 09:04 UTC, merged