Ming/button and modal
Beam-Data-Company/beam-early-access pull request #10
Opened 2021-07-09 05:17 UTC by mingsorawit

### Problems

remove shape in background

### How would the reviewers verify the solutions

### Preflight checklist

- [ ] **Manual testing** has been performed according to the acceptance criteria.
- [ ] _(heavy style change)_ The solution has been tested on the major browser (Chrome, Firefox, Safari, Microsoft Edge).

2021-07-12 07:29 UTC, oukunanan requested changes
**iPhone 5 sceen size**
Overlap logo and button, ask designer what should we do about this.
<img width="309" alt="Screen Shot 2564-07-12 at 14 26 52" src="https://user-images.githubusercontent.com/86279170/125247531-3eacc980-e31d-11eb-9f19-d76e73c113c5.png">

Compare these 2 modal gap

<img width="318" alt="Screen Shot 2564-07-12 at 14 27 00" src="https://user-images.githubusercontent.com/86279170/125247658-60a64c00-e31d-11eb-8a7c-801699468675.png"> 

<img width="311" alt="Screen Shot 2564-07-12 at 14 26 20" src="https://user-images.githubusercontent.com/86279170/125247643-5c7a2e80-e31d-11eb-9da3-7cd8fab732ea.png">

2021-07-12 07:29 UTC, oukunanan commented on components/Header.tsx
> +  const handleClick = () => {
```suggestion
  const toggleModalVisible = () => {
```

2021-07-12 07:29 UTC, oukunanan commented on components/Header.module.css
> +  right: 50px;
We don't need this. 

Hint. Parent element is `display: flex`

2021-07-12 07:29 UTC, oukunanan commented on components/Header.tsx
> +    setShowModal((prev) => !prev)
Nice, can you tell me why we need to use this pattern instead of `setShowModal(!showModal)`?

2021-07-12 07:29 UTC, oukunanan commented on components/StartedModal.module.css
> +}
Create a new component call `Modal.tsx` and apply this CSS to the `Modal` component. Make it reuseable.

2021-07-12 07:29 UTC, oukunanan commented on components/StartedModal.tsx
> +  setVisible: React.Dispatch<React.SetStateAction<boolean>>
```suggestion
  setVisible: () => void
```

2021-07-12 07:29 UTC, oukunanan commented on components/Header.module.css
> +}
Can we make center vertical alignment?
<img width="333" alt="Screen Shot 2564-07-12 at 14 23 17" src="https://user-images.githubusercontent.com/86279170/125247095-c7773580-e31c-11eb-8b2b-e9cc402efa79.png">

2021-07-12 07:29 UTC, oukunanan commented on components/Header.module.css
> +  position: relative;
We going to remove `position: absolute` at `.button`, then don't need this line.

2021-07-12 08:14 UTC, mingsorawit commented on components/Header.tsx
> +    setShowModal((prev) => !prev)
I'm a little confused krub.

2021-07-12 08:18 UTC, oukunanan commented on components/Header.tsx
> +    setShowModal((prev) => !prev)
Do you know difference between `setShowModal((prev) => !prev)` and setShowModal(!showModal)?

2021-07-13 04:43 UTC, oukunanan commented on components/Header.module.css
> +  height: auto;
Do we really need this?

2021-07-13 04:43 UTC, oukunanan commented on components/Header.module.css
> +  padding: auto;
Hm? can we able to use `auto` with `padding`?

2021-07-13 04:43 UTC, oukunanan commented on components/Header.module.css
> +  text-align: center;
I think we can remove this. can you help double check?

2021-07-13 04:43 UTC, oukunanan commented on components/StartedModal.module.css
> +  cursor: pointer;
Currently, we do not allow users to choose `individual account`, and when the mouse hovers the button, shall we still use it as `pointer`?

2021-07-13 04:43 UTC, oukunanan commented on components/SuccessModal.tsx
> +import React from 'react'
Unused `React`

2021-07-13 04:43 UTC, oukunanan commented on components/StartedModal.tsx
> +        <button className={styles.button} disabled={true}>
```suggestion
        <button className={styles.button} disabled>
```

2021-07-14 10:18 UTC, oukunanan approved these changes
Approved in advance.

2021-07-15 07:10 UTC, oukunanan commented on pages/index.tsx
> +  const renderShape = () => {
how about `renderShapes` or `renderShapList`?

2021-07-15 07:10 UTC, oukunanan commented on pages/index.tsx
> +    { data: shape5, name: 'shape5', styleName: styles.shape5 },
Please rename `styleName` to `className`

2021-07-16 05:18 UTC, oukunanan approved these changes

2021-07-19 07:51 UTC, merged