Ming/header footer
Beam-Data-Company/beam-early-access pull request #15
Opened 2021-08-23 12:31 UTC by mingsorawit

### Problems

### How would the reviewers verify the solutions

### Preflight checklist

- [ ] **Manual testing** has been performed according to the acceptance criteria.
- [ ] _(heavy style change)_ The solution has been tested on the major browser (Chrome, Firefox, Safari, Microsoft Edge).

2021-08-24 02:51 UTC, oukunanan requested changes

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.module.css
> +  width: 100%;
Do we really need this? since `div` is `block` element.

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.module.css
> +  display: flex;
Why do we need to put `display: flex` here?

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.module.css
> +  width: 100%;
Do we really need this? since **div** is a `block` element?

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.module.css
> +  width: 100%;
Do we really need this? since **div** is a `block` element?

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.tsx
> +    <div className={styles.container}>
Use `<footer />` for better [semantic html](https://www.w3schools.com/html/html5_semantic_elements.asp)

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.tsx
> +        <div className={styles.logo_container}>
Where is `logo_container` ?

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.tsx
> +        <></>
Remove unnecessary `React.Fragment`

2021-08-24 02:51 UTC, oukunanan commented on components/Footer.tsx
> +      <div className={styles.bottom_section}></div>
Optional: Do not forget to add text `© Beam Data Company Limited 2020. All rights reserved.`

2021-08-24 02:51 UTC, oukunanan commented on components/ImageBox.tsx
> +    <div style={{ width: `${props.width}px` }}>
Do we really need this wrapper? I think `Image` already have  `width` props.

2021-08-24 02:51 UTC, oukunanan commented on components/ImageBox.tsx
> +}
```suggestion
type Props = React.ComponentProps<typeof Image>
```

This will extract all props that available in `Image` component to our `Props` type

2021-08-24 02:51 UTC, oukunanan commented on components/PageBanner.tsx
> +      <Header />
Wrap this with **absolute** parent and set `position: relative` to `styles.continer`

2021-08-24 02:51 UTC, oukunanan commented on components/PageBanner.module.css
> +  padding-left: 50px;
Why do we have to `padding-left: 50px` here and `.container`, it would be nice if only container div can handle this.

2021-08-24 02:51 UTC, oukunanan commented on components/PageBanner.tsx
> +          Privacy by Design
This should come from props. since we going to reuse this component.

2021-08-24 02:51 UTC, oukunanan commented on components/PageBanner.tsx
> +          <ImageBox width={113} src={lockImage} alt="Lock Image" />
This should come from props. since we going to reuse this component.

2021-08-24 02:51 UTC, oukunanan commented on styles/privacypolicy.module.css
> +  height: 1000px;
Please fix this. fixed number of height is not good.
<img width="1434" alt="Screen Shot 2564-08-24 at 09 48 22" src="https://user-images.githubusercontent.com/86279170/130547875-a59e0adf-a388-4b73-8948-fa9f92968333.png">

2021-08-24 02:51 UTC, oukunanan commented on styles/privacypolicy.module.css
> +.main_container {
if this do nothing, I prefer to remove it.

2021-08-24 02:51 UTC, oukunanan commented on components/PageBanner.module.css
> +}
is it still using?

2021-08-24 02:52 UTC, oukunanan commented
Also, add a design link in the PR description and some screens shot.

2021-08-30 12:29 UTC, mingsorawit commented on pages/privacypolicy.tsx
> +    </div>
still have to do this krub

2021-09-01 07:46 UTC, mingsorawit commented on components/Footer.module.css
> +}
done

2021-09-01 07:48 UTC, mingsorawit commented on styles/privacypolicy.module.css
> +.main_container {
because content in this page is mostly in Assistant font krub

2021-09-03 07:38 UTC, mingsorawit commented on pages/privacypolicy.tsx
> +    </div>
done

2021-09-07 04:49 UTC, oukunanan commented on components/Footer.module.css
> +  flex-flow: wrap;
`flex-flow` is shorthand of `flex-direction` and `flex-wrap`. For example 
- `flex-flow: row-reverse wrap`

But if you just want to `wrap`, Please use only `flex-wrap`

2021-09-07 04:49 UTC, oukunanan commented on components/Footer.tsx
> +          <Spacer height={28} heightPhoneResponsive={16} />
I change my mind, prefer something like [this](https://github.com/Beam-Data-Company/beam-early-access/pull/15/commits/1d59a36f31640f92331dad4a1bf2878ce7e40c52#diff-4f34a078049f572f5ebcdf8a3b771ce47c64ec9808cf3acf95a04e1ab72c214dR61)  rather than receive extra props for the responsive size.

2021-09-07 04:49 UTC, oukunanan commented on components/Footer.tsx
> +          <Spacer height={28} heightPhoneResponsive={16} />
So that this [commit](https://github.com/Beam-Data-Company/beam-early-access/pull/15/commits/eef913b73b317a76d4d0c88e0b58e88fa8838d3d) need to fix.

2021-09-07 04:49 UTC, oukunanan commented on pages/privacypolicy.tsx
> +  const res = await fetch('http://localhost:1337/privacy-policy')
Get backend Url from `.env` eg. `${process.env.REACT_STRIPI_URL}/privacy-policy`

2021-09-07 04:49 UTC, oukunanan commented on pages/privacypolicy.tsx
> +        <Text size={20} family="Lexend Deca">
Just curious. What is the value of `font-family` if we didn't pass to this component?

2021-09-20 10:28 UTC, oukunanan approved these changes

2021-09-20 10:30 UTC, merged