Ming/landing page
Beam-Data-Company/beam-early-access pull request #17
Opened 2021-11-24 11:35 UTC by mingbeam

### Problems

### How would the reviewers verify the solutions

![image](https://user-images.githubusercontent.com/90749495/143230464-89d3e938-0f33-4394-be1e-754d55f0340e.png)
![image](https://user-images.githubusercontent.com/90749495/143230584-0db45648-f750-4fc2-b079-2c91ef35fe68.png)
![image](https://user-images.githubusercontent.com/90749495/143230652-c055efca-dd72-4b79-a70c-9c5569c2592d.png)

https://user-images.githubusercontent.com/90749495/143230998-32b863a1-8623-49a0-9159-3bf14cd2cfa3.mp4

![image](https://user-images.githubusercontent.com/90749495/143231168-546b5cbd-88fe-4705-b0b2-a65ffdff606e.png)

### Preflight checklist

- [ ] **Manual testing** has been performed according to the acceptance criteria.
- [ ] _(heavy style change)_ The solution has been tested on the major browser (Chrome, Firefox, Safari, Microsoft Edge).

2021-11-25 03:56 UTC, oukunanan commented on components/Footer.tsx
> +  color: 'white' | 'black'
I think this **props name** is not clear.
```suggestion
  theme: 'white' | 'black'
```
or
```suggestion
  fontColor: 'white' | 'black'
```
or
```suggestion
  variant: 'white' | 'black'
```

2021-11-25 03:56 UTC, oukunanan commented on components/Footer.tsx
> +    <footer className={styles.container} style={{ color: props.color }}>
Can you use `classNames` package here instead of inline-style?

2021-11-25 03:56 UTC, oukunanan commented on components/Footer.tsx
> +            src={props.color === 'black' ? beamLogo : beamLogoWhite}
Before returning the JSX, Can you create a new variable call `isBlackColor` or whatever name related to **prop.color** and use it instead of repeat typing `props.color === 'black'`? it's easy to typo.

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.tsx
> +          src={MediumLogo}
Can you help check with a designer?

Currently:
<img width="1284" alt="Screen Shot 2564-11-25 at 10 26 09" src="https://user-images.githubusercontent.com/86279170/143374753-16dbb4f6-92d1-4ae0-88ce-80f2082ee259.png">

Design: 
<img width="548" alt="Screen Shot 2564-11-25 at 10 29 30" src="https://user-images.githubusercontent.com/86279170/143374867-c7e8de82-1681-4f2d-8e38-216a735aacac.png">

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.module.css
> +  text-align: center;
Why do we need **text-align: center** here?

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.tsx
> +      <div className={styles.title}>
Seem like the title and line are too tight. Can you add some space here?

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.tsx
> +        <Image
Look like you break a little ratio of the image. Maybe we can start using `object-fit`?

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.module.css
> +  margin: auto;
Remove this and add `align-items: center` to `.title`

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/IntroSection.module.css
> +  width: calc(100vw + 80px);
Do we really need `calc`?

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/IntroSection.tsx
> +      <div className={styles.image_description}>
I prefer **render the image description with image**. Do not separate them because Its hard to calculate the position.

2021-11-25 03:56 UTC, oukunanan commented on components/landing_page/IntroSection.module.css
> +}
Once we render the description with the image then we can remove these styles.

2021-11-25 03:57 UTC, oukunanan commented
I'm not finish with the review but you can fix the issue first

2021-11-25 09:42 UTC, oukunanan requested changes
Also fix this error na kub.
<img width="465" alt="Screen Shot 2564-11-25 at 16 17 22" src="https://user-images.githubusercontent.com/86279170/143417458-c3864f58-a0af-4c5e-9d19-d03b9d443ce0.png">

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/InfoSection.tsx
> +type infoType = {
Can we use capitalize?

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/InfoSection.tsx
> +          <div>
Why do we need this div?

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/InfoSection.tsx
> +        <div>
is it required for this div?

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/InfoSection.module.css
> +  padding-right: 40px;
Why not use **margin** since we want to create some space for 2 items?

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCardCarousel.tsx
> +      </button>
Create **Button** component and accept variant props something like `outline | contained` or `primary | secondary`

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCardCarousel.tsx
> +      </button>
Design ref: https://zpl.io/VkoL7Jv

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCardCarousel.module.css
> +    transform: translateX(calc(-500px * 6));
Please add the comment that where do -500 and 6 come from

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCardCarousel.module.css
> +}
Move this to the Button component.

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCard.tsx
> +        >{`Read ${props.industry} case studies`}</Text>
I think this should be the Link component

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCard.tsx
> +        {props.description}
This can be a longgggg description. How would be handling this? [Hint](https://css-tricks.com/almanac/properties/l/line-clamp/)

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCard.tsx
> +            {props.companyName}
Please handle case either name or companyName have a **long** string character.

2021-11-25 09:42 UTC, oukunanan commented on components/landing_page/PartnerCardCarousel.module.css
> +  display: inline-flex;
Oh, I never use this one. Can you elaborate on this?

2021-11-26 10:16 UTC, mingbeam commented on components/Footer.tsx
> +  color: 'white' | 'black'
changed to variant

2021-11-26 10:16 UTC, mingbeam commented on components/Footer.tsx
> +    <footer className={styles.container} style={{ color: props.color }}>
done

2021-11-26 10:16 UTC, mingbeam commented on components/Footer.tsx
> +            src={props.color === 'black' ? beamLogo : beamLogoWhite}
done

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.tsx
> +          src={MediumLogo}
background removed

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.module.css
> +  text-align: center;
removed

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.tsx
> +      <div className={styles.title}>
added 10px margin

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.tsx
> +        <Image
still have to do this

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.module.css
> +  margin: auto;
done

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/InfoSection.tsx
> +type infoType = {
done

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/InfoSection.tsx
> +          <div>
removed

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/InfoSection.tsx
> +        <div>
removed

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/InfoSection.module.css
> +  padding-right: 40px;
changed to margin

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/PartnerCardCarousel.tsx
> +      </button>
created Button component

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/PartnerCardCarousel.module.css
> +    transform: translateX(calc(-500px * 6));
added

2021-11-26 10:16 UTC, mingbeam commented on components/landing_page/PartnerCardCarousel.module.css
> +}
done

2021-11-26 10:17 UTC, mingbeam commented on components/landing_page/PartnerCard.tsx
> +        >{`Read ${props.industry} case studies`}</Text>
done

2021-11-26 10:17 UTC, mingbeam commented on components/landing_page/PartnerCard.tsx
> +        {props.description}
done

2021-11-26 10:17 UTC, mingbeam commented on components/landing_page/PartnerCard.tsx
> +            {props.companyName}
done

2021-11-29 03:37 UTC, oukunanan commented on components/landing_page/IntroSection.tsx
> +      <div className={styles.image_description}>
Forget it for now.

2021-11-29 04:01 UTC, oukunanan reviewed
Continue on mobile responsive.

2021-12-07 05:53 UTC, mingbeam commented on components/landing_page/FeaturedOnSection.module.css
> +}
use margin at .title and it gives a different result ah krub

2021-12-07 05:53 UTC, mingbeam commented on components/landing_page/InfoSection.tsx
> +          <div>
removed

2021-12-08 03:33 UTC, oukunanan commented on components/landing_page/FeaturedOnSection.module.css
> +}
Oh, my bad on this one.

2021-12-23 07:41 UTC, oukunanan approved these changes
- Please update all content for the production
- I think we can temporarily remove the `Read all articles` button since we don't have any articles.
- Cannot enter either Bangkok or Forbes post article.
- Remove all links that are not ready within the footer.
- Link play store and apple store link.
- Please update social media links.
- Please update the `A trusted payments provider` section (Maybe ask P'Win)
- Please update `Why merchants enjoy Beam`
- Image of `Accept all payment methods & model` get cut off.

Responsive is work okay.

2022-01-14 05:01 UTC, oukunanan commented
Can you help extend the scrollable here to the full width of the screen?
https://user-images.githubusercontent.com/86279170/149454257-fb8105a7-61ea-4a9c-a559-ab4370e954dc.mp4

2022-01-21 10:00 UTC, merged