Ming/get started page
Beam-Data-Company/beam-early-access pull request #22
Opened 2022-01-29 14:13 UTC by mingbeam

### Problems

- create lifestyle picture animation for banner
- create get started banner with animated background picture
- create a signup form for get started page
- create api to connect the signup form with mailchimp
- create get started page and implement all the created components
### How would the reviewers verify the solutions

### Preflight checklist

- [ ] **Manual testing** has been performed according to the acceptance criteria.
- [ ] _(heavy style change)_ The solution has been tested on the major browser (Chrome, Firefox, Safari, Microsoft Edge).

2022-01-31 04:20 UTC, oukunanan commented on styles/getstarted.module.css
> +}
Unused className?

2022-01-31 04:20 UTC, oukunanan commented on styles/getstarted.module.css
> +}
Unuse className?

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/GetStartedSignupForm.tsx
> +  /^(([+\\]+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/
We should avoid repetitive code as a [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

<img width="392" alt="Screen Shot 2565-01-31 at 11 07 36" src="https://user-images.githubusercontent.com/86279170/151737588-f921fb55-7019-4246-8d3d-f3346680922c.png">

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/GetStartedSignupForm.tsx
> +          <Form className={styles.form_container}>
**Optional but I will give a task for refactoring for sure**: I think we can extract this into our own component.
<img width="393" alt="Screen Shot 2565-01-31 at 11 12 00" src="https://user-images.githubusercontent.com/86279170/151737934-90b69c9b-1baa-43cf-a3a3-12f8cc76b4a3.png">

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/LifestylePicAnimation.module.css
> +.bg {
Better naming

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/LifestylePicAnimation.tsx
> +    <div>
How about a fragment?

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/LifestylePicAnimation.tsx
> +  const [index, set] = useState(0)
```suggestion
  const [imageIndex, setimageIndex] = useState(0)
```

2022-01-31 04:20 UTC, oukunanan commented on components/early_birds/LifestylePicAnimation.tsx
> +  const [index, set] = useState(0)
or slide

2022-02-02 02:10 UTC, mingbeam commented on components/early_birds/GetStartedBanner.module.css
> +  overflow: hidden;
removed

2022-02-02 02:10 UTC, mingbeam commented on pages/getstarted.tsx
> +      <p className={styles.description}>
changed to h3

2022-02-02 02:10 UTC, mingbeam commented on pages/getstarted.tsx
> +        </Text>
done

2022-02-02 02:11 UTC, mingbeam commented on pages/getstarted.tsx
> +        {mounted && (
yes, it works for this page but not for freeforthree page krub

2022-02-02 02:11 UTC, mingbeam commented on styles/getstarted.module.css
> +}
removed

2022-02-02 02:11 UTC, mingbeam commented on styles/getstarted.module.css
> +}
removed

2022-02-02 02:13 UTC, mingbeam commented on components/early_birds/GetStartedSignupForm.tsx
> +  /^(([+\\]+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/
havent done this

2022-02-02 02:13 UTC, mingbeam commented on components/early_birds/GetStartedSignupForm.tsx
> +          <Form className={styles.form_container}>
havent done this

2022-02-02 02:13 UTC, mingbeam commented on components/early_birds/LifestylePicAnimation.module.css
> +.bg {
changed to image_container

2022-02-02 02:13 UTC, mingbeam commented on components/early_birds/LifestylePicAnimation.tsx
> +    <div>
changed to a fragment

2022-02-02 02:14 UTC, mingbeam commented on components/early_birds/LifestylePicAnimation.tsx
> +  const [index, set] = useState(0)
changed to slideIndex and setSlideIndex

2022-02-02 03:20 UTC, oukunanan approved these changes
Approved. Please create a PR for refactoring. remove a lot of duplicate code and make it reusable.

2022-02-04 03:20 UTC, oukunanan commented
Label click is not working on `Work Email` and `Store Name`

https://user-images.githubusercontent.com/86279170/152466643-6533d477-aeb2-43dd-9e7c-c1859e6f185c.mp4

2022-02-04 03:21 UTC, oukunanan requested changes
According to my latest comment.  👆🏼

2022-02-04 07:47 UTC, oukunanan approved these changes

2022-02-04 07:58 UTC, merged