Ming/faq page
Beam-Data-Company/beam-early-access pull request #29
Opened 2022-04-01 05:52 UTC by mingbeam

### Problems

- create layout for faq page
- create contact support card
- create english and thai faq pages

### How would the reviewers verify the solutions

![image](https://user-images.githubusercontent.com/90749495/161203186-5349c5d6-8943-4670-92da-f0c8f92b42c4.png)
![image](https://user-images.githubusercontent.com/90749495/161203201-0734706a-8aa8-4336-8aa7-f3ab3bc7fb68.png)

### Preflight checklist

- [ ] **Manual testing** has been performed according to the acceptance criteria.
- [ ] _(heavy style change)_ The solution has been tested on the major browser (Chrome, Firefox, Safari, Microsoft Edge).

2022-04-04 03:59 UTC, oukunanan requested changes
Please add `https://` of a tag.

https://user-images.githubusercontent.com/86279170/161471501-567c0c6b-f5e9-4c60-a03a-e4b2adee0f8f.mp4

2022-04-04 03:59 UTC, oukunanan commented on components/Layout.tsx
> +  isFaq?: boolean
This prop is too generic for the FAQ. Please rename what the props are going to do?

2022-04-04 03:59 UTC, oukunanan commented on components/SideBar.tsx
> +  isFaq?: boolean
Too generic for FAQ. Please rename what the props are going to do?

2022-04-04 03:59 UTC, oukunanan commented on components/Layout.module.css
> +.content_wrapper a {
Noted to self: about a tag.

2022-04-04 03:59 UTC, oukunanan commented on components/SideBar.module.css
> +.container.sticky::-webkit-scrollbar {
`-webkit-` is only with  Chrome, Safari, and Opera. How about Firefox and Edge?

2022-04-04 03:59 UTC, oukunanan commented on components/SideBar.module.css
> +}
Better style this on this [line](https://github.com/Beam-Data-Company/beam-early-access/pull/29/files#diff-2e6066348f1042365f23c2217c2247cd965eb00004f6c871020d618c39b40a99L28)

2022-04-04 03:59 UTC, oukunanan commented on components/faq_page/FaqLayout.tsx
> +import React from 'react'
is this component being use?

2022-04-04 03:59 UTC, oukunanan commented on components/faq_page/ContactSupportCard.tsx
> +      <button className={styles.button}>Contact Support</button>
What happened if click the button?

2022-04-04 09:18 UTC, mingbeam commented on components/faq_page/FaqLayout.tsx
> +import React from 'react'
Actually, this file is not being used anymore, so i'm deleting it and its css krub

2022-04-05 08:40 UTC, mingbeam commented on components/faq_page/ContactSupportCard.tsx
> +      <button className={styles.button}>Contact Support</button>
will link to mailto:info@beamcheckout.com krub

2022-04-07 12:49 UTC, merged